# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_react_development
  password: <%= ENV['USER_DATABASE_PASSWORD'] %>
  username: <%= ENV['USER_DATABASE_USERNAME'] %>
  
test:
  <<: *default
  database: hello_rails_react_test
  password: <%= ENV['USER_DATABASE_PASSWORD'] %>
  username: <%= ENV['USER_DATABASE_USERNAME'] %>

production:
  <<: *default
  database:  hello_rails_react_production
  password: <%= ENV['USER_DATABASE_PASSWORD'] %>
  username: <%= ENV['USER_DATABASE_USERNAME'] %>
